// ═══════════════════════════════════════════════════════════════════════════
// Base de datos de equipo SRD 5.1 – Español de España
// Contiene: Armas, Armaduras, Equipo de Aventurero, Paquetes, Herramientas,
//           Monturas/Vehículos.
// ═══════════════════════════════════════════════════════════════════════════

export const EQUIPO = [

  // ─────────────────────────────── ARMAS SIMPLES CUERPO A CUERPO ────────────
  { nombre: 'Bastón', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '2 pp', peso: '1,8 kg', daño: '1d6 Contundente', propiedades: 'Versátil (1d8)', descripcion: 'Un bastón de madera resistente. Puede empuñarse a dos manos para mayor daño.' },
  { nombre: 'Clava', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '1 pp', peso: '0,9 kg', daño: '1d4 Contundente', propiedades: 'Ligera', descripcion: 'Un garrote tosco de madera.' },
  { nombre: 'Daga', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '2 po', peso: '0,45 kg', daño: '1d4 Perforante', propiedades: 'Sutil, ligera, arrojadiza (6/18 m)', descripcion: 'Hoja corta y versátil. Puede usarse cuerpo a cuerpo o lanzarse.' },
  { nombre: 'Gran clava', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '2 pp', peso: '4,5 kg', daño: '1d8 Contundente', propiedades: 'A dos manos', descripcion: 'Un pesado garrote que requiere ambas manos para blandirlo.' },
  { nombre: 'Hacha de mano', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '5 po', peso: '0,9 kg', daño: '1d6 Cortante', propiedades: 'Ligera, arrojadiza (6/18 m)', descripcion: 'Hacha pequeña apta tanto para el cuerpo a cuerpo como para ser lanzada.' },
  { nombre: 'Hoz', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '1 po', peso: '0,9 kg', daño: '1d4 Cortante', propiedades: 'Ligera', descripcion: 'Herramienta agrícola de hoja curva, usada también como arma improvisada.' },
  { nombre: 'Jabalina', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '5 pp', peso: '0,9 kg', daño: '1d6 Perforante', propiedades: 'Arrojadiza (9/36 m)', descripcion: 'Lanza ligera diseñada para ser arrojada.' },
  { nombre: 'Lanza', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '1 po', peso: '1,35 kg', daño: '1d6 Perforante', propiedades: 'Arrojadiza (6/18 m), versátil (1d8)', descripcion: 'Arma de asta básica, eficaz a una o dos manos.' },
  { nombre: 'Martillo ligero', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '2 po', peso: '0,9 kg', daño: '1d4 Contundente', propiedades: 'Ligera, arrojadiza (6/18 m)', descripcion: 'Martillo pequeño que puede lanzarse.' },
  { nombre: 'Maza', tipo: 'Arma', subtipo: 'Simple cuerpo a cuerpo', coste: '5 po', peso: '1,8 kg', daño: '1d6 Contundente', propiedades: '—', descripcion: 'Arma contundente clásica con cabeza de metal.' },

  // ─────────────────────────── ARMAS SIMPLES A DISTANCIA ────────────────────
  { nombre: 'Arco corto', tipo: 'Arma', subtipo: 'Simple a distancia', coste: '25 po', peso: '0,9 kg', daño: '1d6 Perforante', propiedades: 'Munición (24/96 m), a dos manos', descripcion: 'Arco ligero, rápido y fácil de manejar.' },
  { nombre: 'Ballesta ligera', tipo: 'Arma', subtipo: 'Simple a distancia', coste: '25 po', peso: '2,25 kg', daño: '1d8 Perforante', propiedades: 'Munición (24/96 m), recarga, a dos manos', descripcion: 'Ballesta mecánica que dispara virotes con gran precisión.' },
  { nombre: 'Dardo', tipo: 'Arma', subtipo: 'Simple a distancia', coste: '5 pc', peso: '0,11 kg', daño: '1d4 Perforante', propiedades: 'Sutil, arrojadiza (6/18 m)', descripcion: 'Pequeño proyectil arrojadizo.' },
  { nombre: 'Honda', tipo: 'Arma', subtipo: 'Simple a distancia', coste: '1 pp', peso: '—', daño: '1d4 Contundente', propiedades: 'Munición (9/36 m)', descripcion: 'Tira de cuero para lanzar piedras a distancia.' },

  // ──────────────────────── ARMAS MARCIALES CUERPO A CUERPO ─────────────────
  { nombre: 'Alabarda', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '20 po', peso: '2,7 kg', daño: '1d10 Cortante', propiedades: 'Pesada, alcance, a dos manos', descripcion: 'Arma de asta con cuchilla y punta; ataca a 3 m de distancia.' },
  { nombre: 'Cimitarra', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '25 po', peso: '1,35 kg', daño: '1d6 Cortante', propiedades: 'Sutil, ligera', descripcion: 'Espada curva ligera, ideal para combatientes ágiles.' },
  { nombre: 'Espada corta', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '10 po', peso: '0,9 kg', daño: '1d6 Perforante', propiedades: 'Sutil, ligera', descripcion: 'Espada de hoja recta y corta, rápida y precisa.' },
  { nombre: 'Espada larga', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '15 po', peso: '1,35 kg', daño: '1d8 Cortante', propiedades: 'Versátil (1d10)', descripcion: 'El arma emblemática de los caballeros y guerreros.' },
  { nombre: 'Espadón', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '50 po', peso: '2,7 kg', daño: '2d6 Cortante', propiedades: 'Pesada, a dos manos', descripcion: 'Enorme espada a dos manos con devastador potencial.' },
  { nombre: 'Estoque', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '25 po', peso: '0,9 kg', daño: '1d8 Perforante', propiedades: 'Sutil', descripcion: 'Espada delgada y puntiaguda, pensada para estocadas precisas.' },
  { nombre: 'Guja', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '20 po', peso: '2,7 kg', daño: '1d10 Cortante', propiedades: 'Pesada, alcance, a dos manos', descripcion: 'Arma de asta con hoja ancha, similar a la alabarda.' },
  { nombre: 'Gran hacha', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '30 po', peso: '3,15 kg', daño: '1d12 Cortante', propiedades: 'Pesada, a dos manos', descripcion: 'Hacha de batalla enorme, favorita de los bárbaros.' },
  { nombre: 'Hacha de batalla', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '10 po', peso: '1,8 kg', daño: '1d8 Cortante', propiedades: 'Versátil (1d10)', descripcion: 'Hacha robusta que puede usarse a una o dos manos.' },
  { nombre: 'Látigo', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '2 po', peso: '1,35 kg', daño: '1d4 Cortante', propiedades: 'Sutil, alcance', descripcion: 'Arma flexible que alcanza hasta 3 m, ideal para controlar la distancia.' },
  { nombre: 'Lucero del alba', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '15 po', peso: '1,8 kg', daño: '1d8 Perforante', propiedades: '—', descripcion: 'Maza con cabeza erizada de púas metálicas.' },
  { nombre: 'Martillo de guerra', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '15 po', peso: '0,9 kg', daño: '1d8 Contundente', propiedades: 'Versátil (1d10)', descripcion: 'Martillo militar de cabeza pesada.' },
  { nombre: 'Mayal', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '10 po', peso: '0,9 kg', daño: '1d8 Contundente', propiedades: '—', descripcion: 'Cadena con bola de metal; arma contundente clásica.' },
  { nombre: 'Pica', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '5 po', peso: '8,1 kg', daño: '1d10 Perforante', propiedades: 'Pesada, alcance, a dos manos', descripcion: 'Lanza extremadamente larga usada en formación.' },
  { nombre: 'Pica de guerra', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '5 po', peso: '1,15 kg', daño: '1d8 Perforante', propiedades: '—', descripcion: 'Lanza militar de una mano.' },
  { nombre: 'Tridente', tipo: 'Arma', subtipo: 'Marcial cuerpo a cuerpo', coste: '5 po', peso: '1,8 kg', daño: '1d6 Perforante', propiedades: 'Arrojadiza (6/18 m), versátil (1d8)', descripcion: 'Arma de tres puntas, puede usarse a una o dos manos o ser lanzada.' },

  // ──────────────────────── ARMAS MARCIALES A DISTANCIA ─────────────────────
  { nombre: 'Arco largo', tipo: 'Arma', subtipo: 'Marcial a distancia', coste: '50 po', peso: '0,9 kg', daño: '1d8 Perforante', propiedades: 'Munición (45/180 m), pesada, a dos manos', descripcion: 'Arco potente de largo alcance, el preferido de los exploradores.' },
  { nombre: 'Ballesta de mano', tipo: 'Arma', subtipo: 'Marcial a distancia', coste: '75 po', peso: '1,35 kg', daño: '1d6 Perforante', propiedades: 'Munición (9/36 m), ligera, recarga', descripcion: 'Ballesta compacta que se empuña con una sola mano.' },
  { nombre: 'Ballesta pesada', tipo: 'Arma', subtipo: 'Marcial a distancia', coste: '50 po', peso: '8,1 kg', daño: '1d10 Perforante', propiedades: 'Munición (30/120 m), pesada, recarga, a dos manos', descripcion: 'Ballesta de gran calibre con enorme poder de penetración.' },
  { nombre: 'Cerbatana', tipo: 'Arma', subtipo: 'Marcial a distancia', coste: '10 po', peso: '0,45 kg', daño: '1 Perforante', propiedades: 'Munición (7,5/30 m), recarga', descripcion: 'Tubo que dispara agujas; ideal para aplicar venenos.' },
  { nombre: 'Red', tipo: 'Arma', subtipo: 'Marcial a distancia', coste: '1 po', peso: '1,35 kg', daño: '—', propiedades: 'Especial, arrojadiza (1,5/4,5 m)', descripcion: 'Red lastrada que atrapa a las criaturas Grandes o menores.' },

  // ─────────────────────── MUNICIÓN ─────────────────────────────────────────
  { nombre: 'Flechas (20)', tipo: 'Munición', subtipo: 'Munición', coste: '1 po', peso: '0,45 kg', descripcion: 'Carcaj con 20 flechas para arcos.' },
  { nombre: 'Agujas de cerbatana (50)', tipo: 'Munición', subtipo: 'Munición', coste: '1 po', peso: '0,45 kg', descripcion: '50 agujas finas para cerbatana.' },
  { nombre: 'Virotes de ballesta (20)', tipo: 'Munición', subtipo: 'Munición', coste: '1 po', peso: '0,68 kg', descripcion: 'Caja con 20 virotes para ballesta.' },
  { nombre: 'Balas de honda (20)', tipo: 'Munición', subtipo: 'Munición', coste: '4 pc', peso: '0,68 kg', descripcion: '20 piedras pulidas para honda.' },

  // ─────────────────────────── ARMADURAS ────────────────────────────────────
  // Ligeras
  { nombre: 'Armadura acolchada', tipo: 'Armadura', subtipo: 'Ligera', coste: '5 po', peso: '3,6 kg', ca_base: 11, descripcion: 'Capas de tela acolchada cosida. CA 11 + mod. DES. Desventaja en Sigilo.' },
  { nombre: 'Armadura de cuero', tipo: 'Armadura', subtipo: 'Ligera', coste: '10 po', peso: '4,5 kg', ca_base: 11, descripcion: 'Peto y protectores de cuero curtido. CA 11 + mod. DES.' },
  { nombre: 'Armadura de cuero tachonado', tipo: 'Armadura', subtipo: 'Ligera', coste: '45 po', peso: '5,85 kg', ca_base: 12, descripcion: 'Cuero reforzado con remaches metálicos. CA 12 + mod. DES.' },
  // Medias
  { nombre: 'Pieles', tipo: 'Armadura', subtipo: 'Media', coste: '10 po', peso: '5,4 kg', ca_base: 12, descripcion: 'Pieles y pellejos curtidos. CA 12 + mod. DES (máx. +2).' },
  { nombre: 'Cota de malla (camisa)', tipo: 'Armadura', subtipo: 'Media', coste: '50 po', peso: '9 kg', ca_base: 13, descripcion: 'Camisa de anillos metálicos entrelazados. CA 13 + mod. DES (máx. +2).' },
  { nombre: 'Coraza', tipo: 'Armadura', subtipo: 'Media', coste: '400 po', peso: '9 kg', ca_base: 14, descripcion: 'Peto de metal que cubre el torso. CA 14 + mod. DES (máx. +2).' },
  { nombre: 'Semiarmadura', tipo: 'Armadura', subtipo: 'Media', coste: '750 po', peso: '18 kg', ca_base: 15, descripcion: 'Peto y placas parciales. CA 15 + mod. DES (máx. +2). Desventaja en Sigilo.' },
  // Pesadas
  { nombre: 'Cota de anillas', tipo: 'Armadura', subtipo: 'Pesada', coste: '30 po', peso: '18 kg', ca_base: 14, descripcion: 'Anillos metálicos cosidos sobre cuero. CA 14. Desventaja en Sigilo. FUE mín. 13 recomendada.' },
  { nombre: 'Cota de malla', tipo: 'Armadura', subtipo: 'Pesada', coste: '75 po', peso: '24,75 kg', ca_base: 16, descripcion: 'Malla de anillos de acero entrelazados. CA 16. Desventaja en Sigilo. FUE mín. 13.' },
  { nombre: 'Armadura de bandas', tipo: 'Armadura', subtipo: 'Pesada', coste: '200 po', peso: '27 kg', ca_base: 17, descripcion: 'Bandas de metal superpuestas con malla interior. CA 17. Desventaja en Sigilo. FUE mín. 15.' },
  { nombre: 'Armadura de placas', tipo: 'Armadura', subtipo: 'Pesada', coste: '1.500 po', peso: '29,25 kg', ca_base: 18, descripcion: 'Armadura completa de placas de acero. CA 18. Desventaja en Sigilo. FUE mín. 15.' },
  // Escudo
  { nombre: 'Escudo', tipo: 'Armadura', subtipo: 'Escudo', coste: '10 po', peso: '2,7 kg', ca_base: 2, descripcion: 'Escudo de madera o metal. +2 CA. Se lleva en una mano.' },

  // ──────────────────────── EQUIPO DE AVENTURERO ────────────────────────────
  { nombre: 'Ábaco', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '0,9 kg', descripcion: 'Instrumento de cálculo con cuentas deslizantes.' },
  { nombre: 'Aceite (frasco)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pp', peso: '0,45 kg', descripcion: 'Frasco de aceite inflamable. Puede usarse con antorchas o como arma improvisada.' },
  { nombre: 'Agua bendita (frasco)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '0,45 kg', descripcion: 'Agua consagrada. Como acción, puede arrojarse a fiends y no-muertos infligiendo 2d6 de daño radiante.' },
  { nombre: 'Antídoto (vial)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '50 po', peso: '—', descripcion: 'Da ventaja en salvaciones contra veneno durante 1 hora.' },
  { nombre: 'Antorcha', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pc', peso: '0,45 kg', descripcion: 'Ilumina luz brillante a 6 m y tenue otros 6 m durante 1 hora.' },
  { nombre: 'Ariete portátil', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '4 po', peso: '15,75 kg', descripcion: '+4 a pruebas de FUE para derribar puertas. Otro personaje ayudando da ventaja.' },
  { nombre: 'Bálsamo de curación', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '—', descripcion: 'Kit de vendas y ungüentos. Estabiliza a una criatura con 0 pg.' },
  { nombre: 'Baúl', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '11,25 kg', descripcion: 'Contenedor grande de madera con tapa.' },
  { nombre: 'Bolsa de componentes', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '0,9 kg', descripcion: 'Bolsa de cuero impermeable con compartimentos para componentes de hechizos.' },
  { nombre: 'Bola de rodamientos (bolsa de 1.000)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '0,9 kg', descripcion: 'Cubre un área de 3x3 m. Las criaturas deben superar CD 10 DES o caer derribadas.' },
  { nombre: 'Bolsa pequeña', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pp', peso: '0,45 kg', descripcion: 'Saco de tela o cuero para guardar objetos sueltos.' },
  { nombre: 'Botella de cristal', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '0,9 kg', descripcion: 'Frasco de cristal con tapa hermética.' },
  { nombre: 'Brújula', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '—', descripcion: 'Instrumento de navegación que señala al norte.' },
  { nombre: 'Cadena (3 m)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '4,5 kg', descripcion: 'Cadena de hierro. CA 20, 10 pg. Se puede romper con CD 20 de FUE.' },
  { nombre: 'Campana', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '—', descripcion: 'Pequeña campana de metal.' },
  { nombre: 'Candado', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,45 kg', descripcion: 'Candado con llave. CD 15 para abrirlo con ganzúas.' },
  { nombre: 'Candelero', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '0,45 kg', descripcion: 'Soporte para una vela.' },
  { nombre: 'Catalejo', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1.000 po', peso: '0,45 kg', descripcion: 'Los objetos lejanos se ven como si estuvieran al doble de cerca.' },
  { nombre: 'Cazuela de hierro', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '4,5 kg', descripcion: 'Cazuela de hierro fundido para cocinar.' },
  { nombre: 'Cesta', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '4 pp', peso: '0,9 kg', descripcion: 'Cesta de mimbre para transportar objetos.' },
  { nombre: 'Cuerda de cáñamo (15 m)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '4,5 kg', descripcion: 'Cuerda resistente. 2 pg, se rompe con CD 17 de FUE.' },
  { nombre: 'Cuerda de seda (15 m)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '2,25 kg', descripcion: 'Cuerda ligera y fuerte. 2 pg, se rompe con CD 17 de FUE.' },
  { nombre: 'Cubo', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pc', peso: '0,9 kg', descripcion: 'Cubo de madera para agua u otros líquidos.' },
  { nombre: 'Embudo de metal', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '0,9 kg', descripcion: 'Embudo de estaño para trasvasar líquidos.' },
  { nombre: 'Equipo de escalada', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '5,4 kg', descripcion: 'Clavos, botas con suela de hierro, guantes y arnés. Ventaja en pruebas de escalada.' },
  { nombre: 'Eslabón y pedernal', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pp', peso: '0,45 kg', descripcion: 'Permite encender un fuego. Encender una antorcha tarda 1 acción.' },
  { nombre: 'Espejo de acero', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '0,23 kg', descripcion: 'Espejo pequeño de acero pulido.' },
  { nombre: 'Esposas', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '2,7 kg', descripcion: 'Grilletes de hierro. CD 20 FUE para liberarse o CD 15 con ganzúas.' },
  { nombre: 'Farol con capucha', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '0,9 kg', descripcion: 'Luz brillante 9 m, tenue 9 m más. Consume aceite (6 horas por frasco). Se puede tapar.' },
  { nombre: 'Farol de bullseye', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,9 kg', descripcion: 'Cono de luz brillante de 18 m y tenue otros 18 m. Consume aceite (6 horas).' },
  { nombre: 'Frasquito de tinta', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '—', descripcion: 'Pequeño frasco con tinta negra.' },
  { nombre: 'Gancho de agarre', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '1,8 kg', descripcion: 'Garfio metálico que se ata a una cuerda para escalar o anclar.' },
  { nombre: 'Ganzúas', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '0,45 kg', descripcion: 'Set de herramientas para abrir cerraduras. Necesita competencia con herramientas de ladrón.' },
  { nombre: 'Jabón', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 pc', peso: '—', descripcion: 'Pastilla de jabón para la higiene.' },
  { nombre: 'Jarra', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 pc', peso: '1,8 kg', descripcion: 'Jarra de barro para líquidos.' },
  { nombre: 'Kit de disfraz', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '1,35 kg', descripcion: 'Cosméticos, tintes capilares y pequeñas piezas para alterar tu apariencia.' },
  { nombre: 'Libro', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '2,25 kg', descripcion: 'Libro en blanco con 150 páginas de vitela.' },
  { nombre: 'Libro de conjuros', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '50 po', peso: '1,35 kg', descripcion: 'Libro encuadernado en cuero para que un mago registre sus conjuros.' },
  { nombre: 'Lupa', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '100 po', peso: '—', descripcion: 'Lente que puede usarse para encender fuego con la luz del sol o como foco arcano.' },
  { nombre: 'Manta', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pp', peso: '1,35 kg', descripcion: 'Manta de lana para dormir.' },
  { nombre: 'Martillo', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '1,35 kg', descripcion: 'Martillo para clavar clavos y piquetas.' },
  { nombre: 'Mochila', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '2,25 kg', descripcion: 'Mochila de cuero con capacidad para unos 14 kg de objetos.' },
  { nombre: 'Odre', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 pp', peso: '2,25 kg (lleno)', descripcion: 'Recipiente de cuero para transportar agua o vino.' },
  { nombre: 'Pala', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '2,25 kg', descripcion: 'Pala de hierro para cavar.' },
  { nombre: 'Palanca', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '2,25 kg', descripcion: 'Barra de hierro. Ventaja en pruebas de FUE para abrir o forzar.' },
  { nombre: 'Papel (hoja)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 pp', peso: '—', descripcion: 'Hoja de papel fino para escribir.' },
  { nombre: 'Pértiga (3 m)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pc', peso: '3,15 kg', descripcion: 'Vara de madera de 3 metros para sondear trampas a distancia.' },
  { nombre: 'Pergamino (hoja)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pp', peso: '—', descripcion: 'Hoja de pergamino para escribir o copiar conjuros.' },
  { nombre: 'Piquetas de hierro (10)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '2,25 kg', descripcion: 'Diez clavos grandes de hierro para asegurar cuerdas o tiendas.' },
  { nombre: 'Pluma de escribir', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 pc', peso: '—', descripcion: 'Pluma de ave para escribir con tinta.' },
  { nombre: 'Poción de curación', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '50 po', peso: '0,23 kg', descripcion: 'Recupera 2d4+2 puntos de golpe al beberla.' },
  { nombre: 'Raciones (1 día)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pp', peso: '0,9 kg', descripcion: 'Comida seca para un día: cecina, frutos secos, galletas.' },
  { nombre: 'Reloj de arena', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '25 po', peso: '0,45 kg', descripcion: 'Mide intervalos de un minuto.' },
  { nombre: 'Ropas corrientes', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pp', peso: '1,35 kg', descripcion: 'Ropa de campesinado: camisa, pantalón, zapatos.' },
  { nombre: 'Ropas de viaje', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '1,8 kg', descripcion: 'Ropas resistentes para la aventura: botas, capa, cinturón.' },
  { nombre: 'Ropas elegantes', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '15 po', peso: '2,7 kg', descripcion: 'Vestimenta fina propia de nobles y diplomáticos.' },
  { nombre: 'Ropas de explorador', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '1,8 kg', descripcion: 'Túnica, botas altas, guantes y capa con capucha. Ideales para viajeros.' },
  { nombre: 'Saco', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pc', peso: '0,23 kg', descripcion: 'Saco de tela que puede contener hasta 14 kg.' },
  { nombre: 'Saco de dormir', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '3,15 kg', descripcion: 'Saco aislante para dormir al aire libre.' },
  { nombre: 'Silbato', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 pc', peso: '—', descripcion: 'Pequeño silbato de estaño para señales.' },
  { nombre: 'Símbolo sagrado', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '0,45 kg', descripcion: 'Amuleto, emblema o relicario sagrado. Foco de lanzamiento para clérigos y paladines.' },
  { nombre: 'Tienda de campaña (2 personas)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '9 kg', descripcion: 'Refugio portátil de lona para dos personas.' },
  { nombre: 'Tiza (1 pieza)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pc', peso: '—', descripcion: 'Pieza de tiza para marcar superficies.' },
  { nombre: 'Tonel', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '2 po', peso: '31,5 kg', descripcion: 'Barril de madera con capacidad de 150 litros.' },
  { nombre: 'Trampa de caza', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '11,25 kg', descripcion: 'Cepo con dientes. CD 13 DES o la criatura queda inmovilizada y recibe 1d4 perforante.' },
  { nombre: 'Vara (foco arcano)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,45 kg', descripcion: 'Varita de madera o metal, usada como foco de lanzamiento de conjuros.' },
  { nombre: 'Varita (foco arcano)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,45 kg', descripcion: 'Varita fina. Foco arcano para magos, brujos y hechiceros.' },
  { nombre: 'Varilla (foco arcano)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,9 kg', descripcion: 'Varilla de metal o cristal. Foco arcano.' },
  { nombre: 'Orbe (foco arcano)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '20 po', peso: '1,35 kg', descripcion: 'Esfera de cristal, piedra o vidrio. Foco arcano.' },
  { nombre: 'Báculo (foco arcano)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '1,8 kg', descripcion: 'Bastón largo de madera tallada. Foco arcano.' },
  { nombre: 'Foco druídico – Rama de muérdago', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '—', descripcion: 'Rama de muérdago como foco de lanzamiento para druidas.' },
  { nombre: 'Foco druídico – Totem', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 po', peso: '—', descripcion: 'Tótem de madera tallada como foco druídico.' },
  { nombre: 'Foco druídico – Bastón de madera', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '5 po', peso: '1,8 kg', descripcion: 'Bastón vivo con brotes verdes. Foco druídico.' },
  { nombre: 'Foco druídico – Vara de tejo', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '10 po', peso: '0,9 kg', descripcion: 'Vara tallada en madera de tejo. Foco druídico.' },
  { nombre: 'Vela', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '1 pc', peso: '—', descripcion: 'Luz tenue en un radio de 1,5 m durante 1 hora.' },
  { nombre: 'Veneno básico (vial)', tipo: 'Equipo', subtipo: 'Equipo de aventurero', coste: '100 po', peso: '—', descripcion: 'Puedes aplicarlo a un arma. La siguiente criatura golpeada debe superar CD 10 CON o recibe 1d4 veneno extra.' },

  // ──────────────────── PAQUETES DE EQUIPO ──────────────────────────────────
  { nombre: 'Paquete de Burglar', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '16 po', peso: '—', descripcion: 'Incluye: mochila, bolsa de 1.000 bolas de rodamiento, 3 m de cordel, campana, 5 velas, palanca, martillo, 10 piquetas, farol con capucha, 2 frascos de aceite, raciones (5 días), eslabón y pedernal, odre, 15 m de cuerda de cáñamo.' },
  { nombre: 'Paquete de Diplomático', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '39 po', peso: '—', descripcion: 'Incluye: baúl, 2 cajas de mapas/pergaminos, ropas elegantes, frasquito de tinta, pluma de escribir, farol, 2 frascos de aceite, 5 hojas de papel, vial de perfume, cera selladora, jabón.' },
  { nombre: 'Paquete de Dungeoneo', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '12 po', peso: '—', descripcion: 'Incluye: mochila, palanca, martillo, 10 piquetas, 10 antorchas, eslabón y pedernal, raciones (10 días), odre, 15 m de cuerda de cáñamo.' },
  { nombre: 'Paquete de Artista', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '40 po', peso: '—', descripcion: 'Incluye: mochila, saco de dormir, 2 disfraces, 5 velas, raciones (5 días), odre, kit de disfraz.' },
  { nombre: 'Paquete de Explorador', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '10 po', peso: '—', descripcion: 'Incluye: mochila, saco de dormir, kit de comidas, eslabón y pedernal, 10 antorchas, raciones (10 días), odre, 15 m de cuerda de cáñamo.' },
  { nombre: 'Paquete de Sacerdote', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '19 po', peso: '—', descripcion: 'Incluye: mochila, manta, 10 velas, eslabón y pedernal, caja de limosnas, 2 bloques de incienso, incensario, vestiduras, raciones (2 días), odre.' },
  { nombre: 'Paquete de Erudito', tipo: 'Paquete', subtipo: 'Paquete de equipo', coste: '40 po', peso: '—', descripcion: 'Incluye: mochila, libro de conocimiento, frasquito de tinta, pluma de escribir, 10 hojas de pergamino, bolsa pequeña de arena, cuchillo pequeño.' },

  // ──────────────────── HERRAMIENTAS DE ARTESANO ────────────────────────────
  { nombre: 'Herramientas de alquimista', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '50 po', peso: '3,6 kg', descripcion: 'Dos vasos de cristal, un soporte de metal, un alambique de cristal, un agitador y un mortero.' },
  { nombre: 'Herramientas de cervecero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '20 po', peso: '4,1 kg', descripcion: 'Caldero de cobre, sifón, manguera, filtro, un barril y varias jarras.' },
  { nombre: 'Herramientas de calígrafo', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '10 po', peso: '2,25 kg', descripcion: 'Tintas especiales, plumillas y pergaminos de práctica.' },
  { nombre: 'Herramientas de carpintero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '8 po', peso: '2,7 kg', descripcion: 'Sierra, martillo, clavos, escuadra y cepillo de madera.' },
  { nombre: 'Herramientas de cartógrafo', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '15 po', peso: '2,7 kg', descripcion: 'Pluma, tinta, pergaminos, compás, calibrador y regla.' },
  { nombre: 'Herramientas de curtidor', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '5 po', peso: '2,25 kg', descripcion: 'Cuchillo, tenaza, sal y mazo para trabajar cuero y pieles.' },
  { nombre: 'Herramientas de herrero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '20 po', peso: '3,6 kg', descripcion: 'Martillo, tenazas, fuelle, yunque pequeño y carbón.' },
  { nombre: 'Herramientas de hojalatero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '50 po', peso: '4,5 kg', descripcion: 'Tijeras de hojalatero, martillo, soldador y materiales de estaño.' },
  { nombre: 'Herramientas de joyero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '25 po', peso: '0,9 kg', descripcion: 'Sierra fina, martillo pequeño, limas, lupa y tenazas de precisión.' },
  { nombre: 'Herramientas de albañil', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '10 po', peso: '3,6 kg', descripcion: 'Paleta, cincel, nivel, escuadra y martillo de albañil.' },
  { nombre: 'Herramientas de pintor', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '10 po', peso: '2,25 kg', descripcion: 'Caballete, lienzo, pinceles, paleta y frascos de pintura.' },
  { nombre: 'Herramientas de alfarero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '10 po', peso: '1,35 kg', descripcion: 'Torno manual, espátulas, herramientas de modelado y un cuchillo.' },
  { nombre: 'Herramientas de soplador de vidrio', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '30 po', peso: '2,25 kg', descripcion: 'Caña de soplar, pinzas, bloque de madera y moldes metálicos.' },
  { nombre: 'Herramientas de tejedor', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '1 po', peso: '2,25 kg', descripcion: 'Telar portátil, agujas, hilos y tijeras.' },
  { nombre: 'Herramientas de zapatero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '5 po', peso: '2,25 kg', descripcion: 'Martillo, cuchillo, hilo, horma y tiras de cuero.' },
  { nombre: 'Herramientas de tallista', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '1 po', peso: '2,25 kg', descripcion: 'Cuchillo de tallar, gubia y una piedra de afilar.' },
  { nombre: 'Herramientas de cocinero', tipo: 'Herramienta', subtipo: 'Herramientas de artesano', coste: '1 po', peso: '3,6 kg', descripcion: 'Cazuela, cuchillo, tenedor, cuchara y especias variadas.' },

  // ──────────────────── OTRAS HERRAMIENTAS ──────────────────────────────────
  { nombre: 'Herramientas de ladrón', tipo: 'Herramienta', subtipo: 'Herramientas', coste: '25 po', peso: '0,45 kg', descripcion: 'Lima, ganzúas, espejo pequeño, tijeras y pinzas. Necesarias para abrir cerraduras y desactivar trampas.' },
  { nombre: 'Herramientas de navegante', tipo: 'Herramienta', subtipo: 'Herramientas', coste: '25 po', peso: '0,9 kg', descripcion: 'Sextante, brújula, calibrador, regla, pergamino y tinta.' },
  { nombre: 'Kit de envenenador', tipo: 'Herramienta', subtipo: 'Herramientas', coste: '50 po', peso: '0,9 kg', descripcion: 'Viales, mortero, reactivos y un manual. Permite crear venenos.' },
  { nombre: 'Kit de falsificador', tipo: 'Herramienta', subtipo: 'Herramientas', coste: '15 po', peso: '2,25 kg', descripcion: 'Papeles, tintas, plumas, sellos, pan de oro y cera. Permite crear documentos falsos.' },
  { nombre: 'Kit de herbolario', tipo: 'Herramienta', subtipo: 'Herramientas', coste: '5 po', peso: '1,35 kg', descripcion: 'Pinzas, mortero, bolsas y prensa. Permite identificar y preparar plantas medicinales.' },

  // ──────────────────── JUEGOS ──────────────────────────────────────────────
  { nombre: 'Juego de dados', tipo: 'Herramienta', subtipo: 'Juego', coste: '1 pp', peso: '—', descripcion: 'Un juego de dados con los que apostar.' },
  { nombre: 'Baraja de cartas', tipo: 'Herramienta', subtipo: 'Juego', coste: '5 pp', peso: '—', descripcion: 'Baraja de naipes para juegos de azar.' },
  { nombre: 'Juego de ajedrez de dragón', tipo: 'Herramienta', subtipo: 'Juego', coste: '1 po', peso: '0,23 kg', descripcion: 'Tablero y piezas para un juego de estrategia popular en los Reinos.' },
  { nombre: 'Juego de las Tres Dragones', tipo: 'Herramienta', subtipo: 'Juego', coste: '1 po', peso: '—', descripcion: 'Juego de apuestas y farol con cartas especiales.' },

  // ──────────────────── INSTRUMENTOS MUSICALES ──────────────────────────────
  { nombre: 'Chirimía', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '2 po', peso: '0,45 kg', descripcion: 'Instrumento de viento de doble lengüeta, estridente y penetrante.' },
  { nombre: 'Cuerno', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '3 po', peso: '0,9 kg', descripcion: 'Cuerno de animal usado como instrumento de viento.' },
  { nombre: 'Dulcémele', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '25 po', peso: '4,5 kg', descripcion: 'Instrumento de cuerda percutida que se toca con mazas.' },
  { nombre: 'Flauta', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '2 po', peso: '0,45 kg', descripcion: 'Flauta travesera de madera o metal.' },
  { nombre: 'Flauta de pan', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '12 po', peso: '0,9 kg', descripcion: 'Serie de tubos de caña de distintas longitudes.' },
  { nombre: 'Gaita', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '30 po', peso: '2,7 kg', descripcion: 'Instrumento de viento con fuelle y varios tubos.' },
  { nombre: 'Laúd', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '35 po', peso: '0,9 kg', descripcion: 'Instrumento de cuerda pulsada con cuerpo de pera.' },
  { nombre: 'Lira', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '30 po', peso: '0,9 kg', descripcion: 'Instrumento de cuerda con marco en forma de U.' },
  { nombre: 'Tambor', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '6 po', peso: '1,35 kg', descripcion: 'Tambor de mano con parche de cuero tensado.' },
  { nombre: 'Viola', tipo: 'Herramienta', subtipo: 'Instrumento musical', coste: '30 po', peso: '0,45 kg', descripcion: 'Instrumento de cuerda frotada, precursora del violín.' },

  // ──────────────────── MONTURAS Y VEHÍCULOS ────────────────────────────────
  { nombre: 'Burro / Mula', tipo: 'Montura', subtipo: 'Montura', coste: '8 po', peso: '—', descripcion: 'Animal de carga. Velocidad 12 m. Capacidad de carga 210 kg.' },
  { nombre: 'Caballo de monta', tipo: 'Montura', subtipo: 'Montura', coste: '75 po', peso: '—', descripcion: 'Caballo para viajes. Velocidad 18 m.' },
  { nombre: 'Caballo de guerra', tipo: 'Montura', subtipo: 'Montura', coste: '400 po', peso: '—', descripcion: 'Caballo entrenado para el combate. Velocidad 18 m.' },
  { nombre: 'Caballo de tiro', tipo: 'Montura', subtipo: 'Montura', coste: '50 po', peso: '—', descripcion: 'Caballo grande y robusto para arrastrar carros. Velocidad 12 m.' },
  { nombre: 'Camello', tipo: 'Montura', subtipo: 'Montura', coste: '50 po', peso: '—', descripcion: 'Montura para climas desérticos. Velocidad 15 m.' },
  { nombre: 'Elefante', tipo: 'Montura', subtipo: 'Montura', coste: '200 po', peso: '—', descripcion: 'Montura masiva. Velocidad 12 m.' },
  { nombre: 'Mastín', tipo: 'Montura', subtipo: 'Montura', coste: '25 po', peso: '—', descripcion: 'Perro de guerra entrenado. Puede servir de montura para criaturas Pequeñas. Velocidad 12 m.' },
  { nombre: 'Poni', tipo: 'Montura', subtipo: 'Montura', coste: '30 po', peso: '—', descripcion: 'Caballo pequeño, apto para jinetes Pequeños o Medianos. Velocidad 12 m.' },
  { nombre: 'Silla de montar (militar)', tipo: 'Equipo', subtipo: 'Aparejos', coste: '20 po', peso: '13,5 kg', descripcion: 'Silla de montar con estribos y arnés para combate. Ventaja en salvaciones para no ser desmontado.' },
  { nombre: 'Silla de montar (de viaje)', tipo: 'Equipo', subtipo: 'Aparejos', coste: '10 po', peso: '11,25 kg', descripcion: 'Silla estándar para viajes largos.' },
  { nombre: 'Silla de montar (exótica)', tipo: 'Equipo', subtipo: 'Aparejos', coste: '60 po', peso: '18 kg', descripcion: 'Silla especial para monturas acuáticas o voladoras.' },
  { nombre: 'Alforjas', tipo: 'Equipo', subtipo: 'Aparejos', coste: '4 po', peso: '3,6 kg', descripcion: 'Bolsas laterales para una montura.' },
  { nombre: 'Establo (1 día)', tipo: 'Equipo', subtipo: 'Aparejos', coste: '5 pp', peso: '—', descripcion: 'Alojamiento y comida para una montura durante un día.' },
  { nombre: 'Forraje (1 día)', tipo: 'Equipo', subtipo: 'Aparejos', coste: '5 pc', peso: '4,5 kg', descripcion: 'Pienso para una montura durante un día.' },
  { nombre: 'Carro', tipo: 'Vehículo', subtipo: 'Vehículo terrestre', coste: '15 po', peso: '90 kg', descripcion: 'Carro de dos ruedas tirado por animales.' },
  { nombre: 'Carreta', tipo: 'Vehículo', subtipo: 'Vehículo terrestre', coste: '35 po', peso: '180 kg', descripcion: 'Carreta de cuatro ruedas con toldo para viajes.' },
  { nombre: 'Trineo', tipo: 'Vehículo', subtipo: 'Vehículo terrestre', coste: '20 po', peso: '135 kg', descripcion: 'Trineo para terrenos nevados, tirado por animales.' },
  { nombre: 'Barca', tipo: 'Vehículo', subtipo: 'Vehículo acuático', coste: '50 po', peso: '45 kg', descripcion: 'Barca de remos para 1–4 personas. Velocidad 2,5 km/h.' },
  { nombre: 'Galera', tipo: 'Vehículo', subtipo: 'Vehículo acuático', coste: '30.000 po', peso: '—', descripcion: 'Gran buque de guerra a remos. Velocidad 6,5 km/h.' },
  { nombre: 'Barco de vela', tipo: 'Vehículo', subtipo: 'Vehículo acuático', coste: '10.000 po', peso: '—', descripcion: 'Barco mercante a vela. Velocidad 3 km/h.' },
  { nombre: 'Barcaza', tipo: 'Vehículo', subtipo: 'Vehículo acuático', coste: '3.000 po', peso: '—', descripcion: 'Embarcación plana para ríos y canales. Velocidad 1,5 km/h.' },
  { nombre: 'Carabela', tipo: 'Vehículo', subtipo: 'Vehículo acuático', coste: '25.000 po', peso: '—', descripcion: 'Barco de guerra a vela, rápido y maniobrable. Velocidad 4 km/h.' },
];
